[project]
name = "mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiofiles>=24.1.0",
    "httpx>=0.28.1",
    "mcp[cli]>=1.3.0",
    "metapub>=0.5.12",
    "pymupdf4llm>=0.0.17",
]
